[tool.poetry]
name = "shingazidja"
version = "0.1.0"
description = ""
authors = ["Julien Eyriès <julien@eyries.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ghp-import = "^2.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
